{% set magma_version = "2.6.2" %}
{% set magma_commit = "5959b8783e45f1809812ed96ae762f38ee701972" %}

package:
  name: "{{ environ.get('PACKAGE_NAME') }}" 
  version: "{{ environ.get('PACKAGE_VERSION') }}{{ magma_version + '_git+'}}{{  magma_commit[:7] }}"

source:
  git_url: https://bitbucket.org/icl/magma.git
  git_rev: {{ magma_commit }}
  folder: magma

build:
  script_env:
    - PYTORCH_ROCM_ARCH

requirements:
  build:
    - make
    - libstdcxx-ng
    - libgfortran-ng
    - numpy
    - mkl <2022
    - mkl-include <2022

about:
  home: https://bitbucket.org/icl/magma.git
  license: BSD-3-Clause
  summary: Magma linear algebra library on ROCm
  description: |
    Magma is a linear algebra library that provides routines for solving dense and sparse linear systems of equations, and for solving eigenvalue problems. 
