{% set build = 0 %}
{% set rocm_constraints=">=5.3,<5.4" %}
{% if version == '5.4' %}
{% set rocm_constraints=">=5.4,<5.5" %}
{% endif %}

package:
  name: pytorch-rocm
  version: {{ version }}
build:
  number: {{ build }}
  noarch: generic
requirements:
  run:
    - rocm-dev {{ rocm_constraints }}
    - rocm-hip-sdk {{ rocm_constraints }}
    - rocm-ml-libraries {{ rocm_constraints }}
    - miopen-hip-dev {{ rocm_constraints }}
    - libtinfo5
  # None, pytorch should depend on pytorch-rocm
test:
  commands:
    - echo "pytorch-rocm metapackage is created."
about:
  summary: Metapackage to select the PyTorch variant. Use conda's pinning mechanism in your environment to control which variant you want.