{% set build = 0 %}
{% set rocm_constraints=">=6.0,<6.1" %}
{% if version == '6.1' %}
{% set rocm_constraints=">=6.1,<6.2" %}
{% endif %}

package:
  name: pytorch-rocm
  version: {{ version }}
build:
  number: {{ build }}
  noarch: generic
requirements:
  run:
    - rocm {{ rocm_constraints }}
    - miopen-hip-dev {{ rocm_constraints }}
    - libtinfo5
  # None, pytorch should depend on pytorch-rocm
test:
  commands:
    - echo "pytorch-rocm metapackage is created."
about:
  summary: Metapackage to select the PyTorch variant. Use conda's pinning mechanism in your environment to control which variant you want.